application:
  ai-model:
    type: changeme
  telegram:
    bot-token: changeme
    bot-name: ai-bot
  chat-gpt:
    enabled: false
    url: https://api.openai.com
    token: changeme
    model: changeme
    maxTokens: 150
    temperature: 0
  hugging-face:
    enabled: false
    url: changeme
    token: changeme
  http-proxy:
    enabled: false
    host: changeme
    port: changeme
    user: changeme
    password: changeme

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 5000
        metrics:
          enabled: false
